// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyugggqkpgjwvuufhdwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dWdnZ3FrcGdqd3Z1dWZoZHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMjM0NTgsImV4cCI6MjA1Mzg5OTQ1OH0.-9Klhq-JKJebV8XvgduY3WguR00vJ5-YPZMuIlbAT5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);